server {
    listen 443 ssl;
    server_name tab3u.com;
    ssl_certificate /etc/nginx/tab3u.com.cer;
    ssl_certificate_key /etc/nginx/tab3u.com.key;
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;
    
    location / {
        root /var/www/tab3u.com;
        try_files $uri @backend;
    }

    location /tabs/songs/ {
        proxy_ssl_server_name on;
        proxy_set_header Accept-Encoding "";
        proxy_pass https://www.tab4u.com;
        
        sub_filter_once off;
        sub_filter_types text/html;
        
        # Edit Title
        sub_filter '</title>' '</title>-->';
        sub_filter '<title>' '<title>Tab3U</title><!--';

        # Inject JS Script
        sub_filter '<head>' '<head> <script type="text/javascript" src="/inject.js"></script>';
    }

    location @backend {
        proxy_ssl_server_name on;
        proxy_set_header Accept-Encoding "";
        proxy_pass https://www.tab4u.com;    

        sub_filter_once off;
        sub_filter_types text/html;
        
        # Edit Title
        sub_filter '</title>' '</title>-->';
        sub_filter '<title>' '<title>Tab3U</title><!--';
    }
}